version: '3'

services:
  telegraf:
    image: telegraf:latest
    container_name: telegraf
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy: